site_name: caiopeternela.dev
theme:
  icon:
    logo: material/code-tags
  name: material
  features:
    - navigation.sections
  palette:
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Noto Sans
    code: JetBrains Mono
plugins:
  - blog:
      archive: false
      categories_name: Tags
extra:
  generator: false
