site_name: caiopeternela.dev

theme:
  icon:
    logo: material/code-tags
  name: material
  palette:
    - scheme: slate
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    text: Noto Sans
    code: JetBrains Mono

plugins:
  - blog:
      archive: false

nav:
  - Resume:
      index.md
  - Blog:
      blog/index.md

extra:
  generator: false
